### ISSUE TITLE
when new file added, static-cache just return 404 Not Found

### ISSUE THREAD

**Issue by shepherdwind** [koajs/static-cache#30]
I think, when a new file added, staticCache should load file. 

But, now it just return 404 Not Found.

Test code like this:

```
 var fs = require('fs');
 it('add new file should work fine', function (done) {
    var app = koa()
    app.use(staticCache())
    var server = app.listen()
    fs.writeFileSync('a.js', 'hello world');

    request(server)
      .get('/a.js')
      .expect(200, done)
  })
```

**Comment by dead-horse** [comment]
all files are load into memory when app launched, so you can't add file dynamic.

**Comment by dead-horse** [comment]
we can change the logic of `opt.buffer` to make reload work. PR's welcome.
