### ISSUE TITLE
Path separator not unified 

### ISSUE THREAD

**Issue by JixunMoe** [koajs/static-cache#39]
After update from 1.2.0 I have realized that I can't serve static files anymore. Looking inside the module I have found that the path separator mismatch have made the file object never accessible. 

The machine is Windows, and example files object (via console.log) shown below:

```js
{
  '/res\jquery-2.1.1.min.js':
   { path: 'D:\\test\\public\\jquery-2.1.1.min.js',
     cacheControl: undefined,
     maxAge: 0,
     mime: 'application/javascript',
     type: 'application/javascript',
     mtime: 'Sat, 01 Nov 2014 13:52:08 GMT',
     length: 84245,
     md5: '5A7CFh/nmTGW8jyKBzRjBg=='
   }
}
```

And when the url was visited, is looking for `\res\jquery-2.1.1.min.js` inside the files object.

Code setup:
```js
var __PUBLIC_ABS = __dirname  + '/public/';
var staticCache = require('koa-static-cache');
app.use (staticCache(__PUBLIC_ABS, {
	prefix: '/res/'
}));
```

Thanks.

**Comment by JixunMoe** [comment]
My temporary workaround, by changing line 18 to the following:

```js
  options.prefix = (options.prefix || '').replace(/\\|\//g, path.sep).replace(/[\\\/]$/, '') + path.sep
```

**Comment by coderhaoxin** [comment]
@JixunMoe v3.1.1 should fix this

**Comment by JixunMoe** [comment]
Thanks!
