### ISSUE TITLE
Koa 2.0 support

### ISSUE THREAD

**Issue by andyhu** [koajs/static-cache#51]

**Comment by juavidn** [comment]
Is this supported ?

**Comment by andyhu** [comment]
@juavidn No it's not, you'll have to use koa-convert

**Comment by juavidn** [comment]
thank you very much !

**Comment by weizeng** [comment]
var staticCache = require('koa-static-cache');
app.use(convert(staticCache(path.join(__dirname, '../app/chat/public'))));

use koa2, but still not work, my style.css like 
"<!doctype html>
<html lang="en">
<head>"

what can i do?

**Comment by mgol** [comment]
I submitted a PR adding support for Koa 2: #57.
