### ISSUE TITLE
Can not cache the JS file

### ISSUE THREAD

**Issue by JoeBBChen** [koajs/static-cache#53]
like this：

![image](https://cloud.githubusercontent.com/assets/12586787/17362551/208b6f14-59a8-11e6-9ebc-0c109587b99a.png)

I don‘t know why。
help~

**Comment by dead-horse** [comment]
1. make sure you've set `options.maxage`. (that will set cache-control in your js file's response headers)
2. check if you've checked `disable cache` in your devTools.

**Comment by JoeBBChen** [comment]
@dead-horse 
I had set options.maxage and  my browser is not set disable cache.
A more strange question,  I fall back to the previous version of the my code from my gitlab, it can not only cache image but also js file before. But now I run my code ， it does‘t work，and I guarantee that this version of the code is tested to be able to cache JS when it was pushed to my github, and I never edit it.

![image](https://cloud.githubusercontent.com/assets/12586787/17401246/321120da-5a7f-11e6-8a52-bc366115f3dc.png)
’

**Comment by JoeBBChen** [comment]
I solved my problem。I want to speak Chinese, because my English is not good, the expression is not clear in English。I'm still in English and Chinese.
### First
the JS file in my webapp folder are  dynamically generated by webpack。when I run my code， it run the middleware code first， then build my code into webapp folder。

### From the code of the `koa-static-cache`  middleware can be seen
![image](https://cloud.githubusercontent.com/assets/12586787/17455527/97316a38-5bec-11e6-9fac-2f1ed2b266b8.png)

add the file in the static directory ('../webapp' )  to the `filename` variable。

### So the problem is that, before run this code,  webpack is not  generate my JS code in the webappp， so `filename` variable does not include this generated JS。

![image](https://cloud.githubusercontent.com/assets/12586787/17455639/04997008-5bf1-11e6-8d42-170418402974.png)






Sooooo， This is the reason why it has not been able to cache the JS code!!!

## How to solve ？
First run over the code, to generate the JS files, and then re run once again, in order to execute the code about  `koa-static-cache`  middleware to add the generated JS files to the cache.

## This is my personal opinion, I hope you correct me.


# Next is the Chinese session
首先非常抱歉我的中国式英语=。=
### 问题所在
不能缓存 webapp 目录下的的 JS 代码
### 原因
webapp 目录下的 JS 代码是在启动 server（上面截图的 server 文件夹） 端的代码时由 webpack build 出来的，但是在执行 server 端代码使，先执行了  `koa-static-cache`  中间件的代码， 再去 build JS， 因此  `koa-static-cache`  那个 `filename` 是不包括那些动态生成的 JS 代码的，所以也就不在缓存的范围中。
### 解决
可以在跑一次代码之后，这时候已经生成了所需的 JS 文件，然后重跑一遍，这时候再执行那个中间件的代码，就可以在 webapp 文件下找到那些 JS 文件，然后把它们加到缓存范围中。

## 这是我个人见解，不低望指出。
