### ISSUE TITLE
app can be view any directory and files

### ISSUE THREAD

**Issue by tonylinyy** [koajs/static-cache#63]
hi
when I use the middleware like this:
  app.use(staticCache(path.resolve(__dirname, '../public'), {
    gzip: true,
    dynamic: true
  }))
anyone can view any directory and files  like this in windows,
http://xxx.xx.xx/..%5c..%5c/xxx
it is very dangerous
how to avoid?

**Comment by tonylinyy** [comment]
we add a middleware like this to void,any better solution?
`app.use(function *(next) {
  let filename = decodeURIComponent(path.normalize(this.path));
  if(filename.indexOf('..')>=0){
    this.status = 200;
    this.body = 'Not Found';
    return;
  }
  yield next;
});`

**Comment by dead-horse** [comment]
closes by #66 #67
