### ISSUE TITLE
How to specify custom mime map definition?

### ISSUE THREAD

**Issue by dickeylth** [koajs/static-cache#69]
[https://github.com/koajs/static-cache/blob/master/index.js#L200](https://github.com/koajs/static-cache/blob/master/index.js#L200)

```js
obj.type = obj.mime = mime.lookup(pathname) || 'application/octet-stream'
```

The code logic here is using `mime-types` to check the corresponding mime type for filepath, however if I want to customize mime type for specific `extname`, I guess it's unavailable currently?

**Comment by dead-horse** [comment]
yes, but you can add a middleware to reset content-type after static-cache middleware.
