### ISSUE TITLE
option.alias redirect not effective in windows

### ISSUE THREAD

**Issue by Ysj291823** [koajs/static-cache#80]
to redirect /swagger-ui.html to /index.html,
in linux it is effective,but windows not.

    const swaggerH5 = path.join(__dirname, '../../app/public');
    app.use(staticCache(swaggerH5, {
      alias: {
        '/swagger-ui.html': '/index.html',
      },
    }, {}));

**Comment by guoguo0202** [comment]
怎么解决的？
