### ISSUE TITLE
length

### ISSUE THREAD

**Issue by jiazhonglin** [koajs/static-cache#86]
HI,
   I'm  using koa-static-cache in my app. my app deploy in the server. when I rollback my app to an old version,my broswer page is broken.
  I serarch the reason.  then I find that when I rollback my app the mtime is ealier than latest one,it cause ctx.length not refresh.       
   Should file.length refresh  whether the mtime old or new?  
![image](https://user-images.githubusercontent.com/15116568/88880278-e50fd400-d25e-11ea-948b-1518e33716f4.png)

**Comment by jiazhonglin** [comment]
this line   ,should  modify  as  ' if  (stats.mtime != file.mtime)'    ?

**Comment by dead-horse** [comment]
looks good to me, can you create a PR to fix this?

**Comment by jiazhonglin** [comment]
sure,  I made  a PR:
https://github.com/koajs/static-cache/pull/87

**Comment by jiazhonglin** [comment]
> looks good to me, can you create a PR to fix this?

https://github.com/koajs/static-cache/pull/92
I  have  made a PR.  Please   take  a  look.
thank  you

**Comment by jiazhonglin** [comment]
> looks good to me, can you create a PR to fix this?

https://github.com/koajs/static-cache/pull/93

I commit  a  new  PR,   but test  can't be  passed , because the test didn't consider the case that  "  file   rollback  ",  in the test file ,file's  mtime  set a later time ,  the  case "file rollback", should be cover.
in consideration of modify  the test file ,may confilect to maintainer's mind, so I  didn't modify it.
can  you  cover this case in the test file ?

**Comment by 3imed-jaberi** [comment]
@dead-horse, @jonathanong, @niftylettuce plz close this issue !
